(define (list-trim-right xs)
   (define (loop xs s sdop)
      (cond ((equal? xs '())
                 s)
            ((char-whitespace? (car xs))
                (loop (cdr xs) s (append sdop (list (car xs)))))
            ((not (char-whitespace? (car xs)))
                (loop (cdr xs) (append s sdop (list (car xs))) '()))))
   (loop xs '() '()))
