(define (read-words)
  (define (loop s1 s)
    (if (eof-object? s)
        '()
        (if (char-whitespace? s)
            (if (not (equal? s1 (string)))
                (cons s1 (loop (string) (read-char)))
                (loop (string) (read-char)))
            (loop (string-append s1 (string s)) (read-char)))))
  (loop (string) (read-char)))
